---
title: "BSA"
author: "Chloe Kim"
output: html_document
---
```{r}
# install necessary packages
library(conflicted)
library(plyr)
library(tidyverse)

# read in csv
dataset <- read.csv("all_seasons.csv")
# get rid of column 1 (index column)
dataset <- dataset[,-1]
# make sure csv was read in correctly
head(dataset)
```

```{r}
# select relevant variables
dataset <- dataset %>% select(player_name, draft_round, draft_number, pts, oreb_pct, dreb_pct, ts_pct, ast_pct, usg_pct)

# deleting rows of players who have the exact same name as other players AND have played less than 5 seasons
dataset <- dataset[-c(142, 4888, 5435, 7654, 8389, 4827, 5164, 5165, 5636, 5644, 6141, 6651, 294, 4705),]
```

```{r}
# this code is for finding players who have played x or more seasons

# create table outputting the number of each player's name occurence
table <- table(dataset$player_name)
# creating a variable containing the names
names <- names(table[table >= 5])

# obtaining index numbers of the 'names' variable in 'dataset'
index <- which(dataset$player_name %in% names)

# subsetting dataset by 'index' and creating a new dataframe
cleaned_dataset <- dataset[index,]
```

```{r}
# replacing occurences of "Undrafted" in dataframe with 0
cleaned_dataset[cleaned_dataset == "Undrafted"] <- 0

# changing data type of draft_round and draft_number columns to numeric
cleaned_dataset$draft_round <- as.numeric(cleaned_dataset$draft_round)

cleaned_dataset$draft_number <- as.numeric(cleaned_dataset$draft_number)

# averaging the columns of each player and creating a dataframe to store these values; each player is designated one row
# player names put in alphabetical order
df <- ddply(cleaned_dataset,.(player_name), plyr::summarize, draft_round=mean(draft_round), draft_number=mean(draft_number), pts=mean(pts), ast_pct=mean(ast_pct), reb_pct=mean(oreb_pct+dreb_pct), ts_pct=mean(ts_pct), usg_pct=mean(usg_pct))
```

```{r}
# read in csv that contains data + championships + all star selections
df <- read.csv("data_champ_allstar.csv")

# normalizing all columns
df$pts <- (df$pts-mean(df$pts))/(sd(df$pts))*100
df$champ <- (df$champ-mean(df$champ))/(sd(df$champ))*100
df$all_star <- (df$all_star-mean(df$all_star))/(sd(df$all_star))*100
df$ast_pct <- (df$ast_pct-mean(df$ast_pct))/sd(df$ast_pct)*100
df$reb_pct <- (df$reb_pct-mean(df$reb_pct))/sd(df$reb_pct)*100
df$ts_pct <- (df$ts_pct-mean(df$ts_pct))/sd(df$ts_pct)*100
df$usg_pct <- (df$usg_pct-mean(df$usg_pct))/sd(df$usg_pct)*100

# changing column names to make more clear what the data represents
colnames(df)[4] <- "pts_pct"
colnames(df)[9] <- "champ_pct"
colnames(df)[10] <- "allstar_pct"

# assigning weights to each factor
weight_champ <- 0.05
weight_ts <- 0.2
weight_usg <- 0.15
weight_pts <- 0.2
weight_ast <- 0.15
weight_reb <- 0.15
weight_allstar <- 0.1

# multiplying each factor by its respective weight, and then assigning values to the respective columns
df$pts_pct <- weight_pts*df$pts_pct
df$ast_pct <- weight_ast*df$ast_pct
df$reb_pct <- weight_reb*df$reb_pct
df$ts_pct <- weight_ts*df$ts_pct
df$usg_pct <- weight_usg*df$usg_pct
df$champ_pct <- weight_champ*df$champ_pct
df$allstar_pct <- weight_allstar*df$allstar_pct

# summing the columns of the factors within each row in order to obtain total score for each player
cols_to_sum <- names(df) %in% c("pts_pct", "ast_pct", "reb_pct", "ts_pct", "usg_pct", "champ_pct", "allstar_pct")
row_sums <- rowSums(df[, cols_to_sum])

# adding 'score' column to 'df'
df$score <- row_sums
head(df)
```

```{r}
# creating scatterplot of each player's score v.s. their respective draft number
plot(df$draft_number, df$score, main="All Player Scores", xlab="draft number", ylab="score", pch = 20, cex = 0.5)
abline(mod <- lm(df$score ~ df$draft_number), col = "red")
# obtaining correlation coefficient
cor(df$draft_number, df$score)

# obtaining the y-intercept and slope of the line of best fit
coef(mod)

# subsetting players who have a score greater than or equal to 30
# df[which(df$score >= 30),]

# creating scatterplot of each player's score v.s. their respective draft number, except those who have draft_number greater than or equal to 70
# this is to better visualize the left side of the graph titled "All Player Scores" without the large draft number outliers
# this graph includes those who were undrafted
draftnum_lessthan_70 <- df[which(df$draft_number<70),]
plot(draftnum_lessthan_70$draft_number, draftnum_lessthan_70$score, main="Scores of Players With Draft Number < 70 (including undrafted)", xlab="draft number", ylab="score", pch = 20, cex = 0.5)
abline(lm(draftnum_lessthan_70$score ~ draftnum_lessthan_70$draft_number), col = "red")
# obtaining correlation coefficient
cor(draftnum_lessthan_70$draft_number, draftnum_lessthan_70$score)

# creating scatterplot of each player's score v.s. their respective draft number, except those who have draft_number greater than or equal to 70
# this is to better visualize the left side of the graph titled "All Player Scores" without the large draft number outliers
# this graph does NOT include those who were undrafted
draftnum_lessthan_70_greaterthan0 <- draftnum_lessthan_70[which(draftnum_lessthan_70$draft_number > 0),]
plot(draftnum_lessthan_70_greaterthan0$draft_number, draftnum_lessthan_70_greaterthan0$score, main="Scores of Players With Draft Number < 70 (excluding undrafted)", xlab="draft number", ylab="score", pch = 20, cex = 0.5)
abline(lm(draftnum_lessthan_70_greaterthan0$score ~ draftnum_lessthan_70_greaterthan0$draft_number), col = "red")

# create table outputting the total number of each different draft round occurence, where 0 = Undrafted
table(df$draft_round)

# subsetting by different draft round from 'df'
draft_round_1 <- df[which(df$draft_round == 1),]
draft_round_2 <- df[which(df$draft_round == 2),]
undrafted <- df[which(df$draft_round == 0),]
# subsetting players with scores > 12 from 'undrafted' to obtain those who had scores over the floor of the y-intercept value obtained earlier as well as for visualization purposes
undrafted_score_greater_than_12 <- undrafted[which(undrafted$score > 12),]

# creating scatterplot of each player's score v.s. their respective draft number (only considering draft round 1)
plot(draft_round_1$draft_number, draft_round_1$score, main="Draft Round 1 Player Scores", xlab="draft number", ylab="score", pch = 20, cex = 0.5)
abline(lm(draft_round_1$score ~ draft_round_1$draft_number), col = "red")
# obtaining correlation coefficient
cor_r1 <- cor(draft_round_1$draft_number, draft_round_1$score)
cat("The correlation coefficient is", cor_r1)

# creating scatterplot of each player's score v.s. their respective draft number (only considering draft round 2)
plot(draft_round_2$draft_number, draft_round_2$score, main="Draft Round 2 Player Scores", xlab="draft number", ylab="score", pch = 20, cex = 0.5)
abline(lm(draft_round_2$score ~ draft_round_2$draft_number), col = "red")
# obtaining correlation coefficient
cor_r2 <- cor(draft_round_2$draft_number, draft_round_2$score)
cat("The correlation coefficient is", cor_r2)

# creating barplot of undrafted players who have a score greater than 12 with their respective scores
par(mar = c(4, 8, 4, 2))
barplot(undrafted_score_greater_than_12$score, names.arg = undrafted_score_greater_than_12$player_name, col = "blue", main = "Undrafted Player Scores Over 12", xlab = "Scores", ylab = "", horiz=T, las=1)

# creating boxplot of players' scores to visualize IQR, outliers, and other statistics with respect to different draft rounds, where 0 = "Undrafted"
boxplot(df$score ~ df$draft_round, xlab = "Draft Round", ylab = "Player Score", main = "Boxplot of Players' Scores By Draft Round")

df[which(df$draft_number>70),]
```

